{'date': '2016.05.16.', 'heart_count': '1,250', 'reply_count': '288', 'play_count': '260,609', 'is_ku': False, 'is_kim': False, 'reply_list': ['窪せせせせせせせせ格巷 数医製 葛掘設馬壱 設持奄壱 鯵硲姶..', '紫燈軒 窪 せせせせ 嬢多暗醤 せせせ 格巷 数移 せせせせ 森管姶 多嬢 せせせせ', '蟹亜呪巷企焼観廃厩号勺拭辞伐帖伸告告告聖級生艦姶疑戚革推^^', '遭走馬惟 馬檎 鈷赤壱 仙衡惟馬檎 角 数奄壱 蝕獣 幻管戚革推. 葛径税 衣引 置壱脊艦陥.~⊇⊇ 硝檎 硝呪系 希 疏精 伐帖伸 誓据 杯艦陥 ~^^', '焼~~~格巷 設背推 遭促~~⊇⊇', '蝕獣 公馬澗惟 蒸革.. 伐帖伸 希 希 被馬掩⊇⊇', 'せせ 数沿..悦汽 茶 神潅 多醸製..益闇 蒸蟹?', '廃厩.掻厩寅級壕形背辞廃厩嬢稽馬壱掻厩嬢稽馬澗壕形宿伐帖伸神匙原製亀鐸背推', '神潅号勺 格巷 仙衡醸嬢推 ぞぞぞ 蝕習  森管姶 詞焼赤柔艦陥~~~郊孜獣畏走幻 廃厩覗稽益轡拭亀 切爽 蟹人爽室推^^', '刃穿 鈷閃推 姥呪馬惟 窪馬獣壱 俗 ~~⊂⊂伸 亜呪 還告告告~~~^^⊂⊂⊂⊂⊂', '葛掘檎 葛掘 森管戚檎 森管 謂謝馬走 壕形燕走 公馬汗惟 校猿? 陥 鞠澗 鈷遭 害切', '告告告 政袴獄鮮昔亜推??? 数汗虞 壕嘉 三革推...', '神潅 食奄 巷狛走備~~せせせせ 遭促 古径帰嬢軒績せせせせ', '紫燈軒 窪~~ 庁悦馬革推.せせせ 葛掘 設馬革推.', '茶蓄檎辞亀 葛掘 格巷 設採硯'], 'order_in_list': 9}
Traceback (most recent call last):
  File "2016_radio.py", line 67, in list_crawl
    click_element = driver.find_element_by_xpath(click_path)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='playlistClip']/li[8]/div/dl/dt/a"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17134 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "2016_radio.py", line 67, in list_crawl
    click_element = driver.find_element_by_xpath(click_path)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='playlistClip']/li[8]/div/dl/dt/a"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17134 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "2016_radio.py", line 67, in list_crawl
    click_element = driver.find_element_by_xpath(click_path)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='playlistClip']/li[8]/div/dl/dt/a"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17134 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "2016_radio.py", line 67, in list_crawl
    click_element = driver.find_element_by_xpath(click_path)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='playlistClip']/li[9]/div/dl/dt/a"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17134 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "2016_radio.py", line 68, in list_crawl
    click_element.click()
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <a class="_click" data-moveclipno="728544" data-playlistno="64406" data-categorycode="ENTER" data-event="moveAnotherClipByUser" href="https://tv.naver.com/v/728544/list/64406" title="鯵益毒 紫櫛引 穿戦?!">...</a> is not clickable at point (957, 604). Other element would receive the click: <a href="#" class="btn btn_top" onclick="goTop();clickcr(this, 'mov.top', '', '', event)" title="...">TOP</a>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17134 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "2016_radio.py", line 67, in list_crawl
    click_element = driver.find_element_by_xpath(click_path)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='playlistClip']/li[9]/div/dl/dt/a"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17134 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "2016_radio.py", line 67, in list_crawl
    click_element = driver.find_element_by_xpath(click_path)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='playlistClip']/li[8]/div/dl/dt/a"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17134 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "2016_radio.py", line 67, in list_crawl
    click_element = driver.find_element_by_xpath(click_path)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='playlistClip']/li[8]/div/dl/dt/a"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17134 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "2016_radio.py", line 67, in list_crawl
    click_element = driver.find_element_by_xpath(click_path)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='playlistClip']/li[8]/div/dl/dt/a"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17134 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "2016_radio.py", line 67, in list_crawl
    click_element = driver.find_element_by_xpath(click_path)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='playlistClip']/li[8]/div/dl/dt/a"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17134 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "2016_radio.py", line 67, in list_crawl
    click_element = driver.find_element_by_xpath(click_path)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='playlistClip']/li[8]/div/dl/dt/a"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17134 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "2016_radio.py", line 67, in list_crawl
    click_element = driver.find_element_by_xpath(click_path)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='playlistClip']/li[10]/div/dl/dt/a"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17134 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "2016_radio.py", line 67, in list_crawl
    click_element = driver.find_element_by_xpath(click_path)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='playlistClip']/li[11]/div/dl/dt/a"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17134 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "2016_radio.py", line 67, in list_crawl
    click_element = driver.find_element_by_xpath(click_path)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='playlistClip']/li[12]/div/dl/dt/a"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17134 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "2016_radio.py", line 68, in list_crawl
    click_element.click()
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 80, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Element <a class="_click" data-moveclipno="841659" data-playlistno="73068" data-categorycode="ENTER" data-event="moveAnotherClipByUser" href="https://tv.naver.com/v/841659/list/73068" title="毘濁戚 採牽澗 '社橿'">...</a> is not clickable at point (959, 624). Other element would receive the click: <a href="#" class="btn btn_top" onclick="goTop();clickcr(this, 'mov.top', '', '', event)" title="...">TOP</a>
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17134 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "2016_radio.py", line 67, in list_crawl
    click_element = driver.find_element_by_xpath(click_path)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='playlistClip']/li[12]/div/dl/dt/a"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17134 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "2016_radio.py", line 67, in list_crawl
    click_element = driver.find_element_by_xpath(click_path)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='playlistClip']/li[12]/div/dl/dt/a"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17134 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "2016_radio.py", line 67, in list_crawl
    click_element = driver.find_element_by_xpath(click_path)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id='playlistClip']/li[11]/div/dl/dt/a"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17134 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "2016_radio.py", line 33, in list_crawl
    date =  driver.find_element_by_xpath('//*[@id="clipInfoArea"]/div[4]/div/dl/dd[3]').text
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 394, in find_element_by_xpath
    return self.find_element(by=By.XPATH, value=xpath)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 978, in find_element
    'value': value})['value']
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: no such element: Unable to locate element: {"method":"xpath","selector":"//*[@id="clipInfoArea"]/div[4]/div/dl/dd[3]"}
  (Session info: chrome=70.0.3538.110)
  (Driver info: chromedriver=2.43.600210 (68dcf5eebde37173d4027fa8635e332711d2874a),platform=Windows NT 10.0.17134 x86_64)


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "2016_radio.py", line 99, in <module>
    nc.list_crawl()
  File "2016_radio.py", line 87, in list_crawl
    self.list_crawl()
  File "2016_radio.py", line 87, in list_crawl
    self.list_crawl()
  File "2016_radio.py", line 87, in list_crawl
    self.list_crawl()
  [Previous line repeated 14 more times]
  File "2016_radio.py", line 37, in list_crawl
    date_strp = datetime.strptime(date, '%Y.%m.%d.')
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\_strptime.py", line 577, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Users\bumso\AppData\Local\Programs\Python\Python37\lib\_strptime.py", line 359, in _strptime
    (data_string, format))
ValueError: time data '溝送' does not match format '%Y.%m.%d.'

C:\Users\bumso\datajournalism-2018\datajournalism-team-1\Bemsoo\navertv_crawler>[20308:25984:1204/194831.586:ERROR:latency_info.cc(144)] RenderWidgetHostImpl::OnSwapCompositorFrame, LatencyInfo vector size 458 is too big.